openapi: 3.0.3
info:
  title: sx-wordle
  description: Simple wordle like game
  version: 1.0.0
servers:
  - url: http://localhost:80
tags:
  - name: wordle
paths:
  /game:
    post:
      summary: Create new game instance
      operationId: createNewGame
      tags:
        - wordle
      parameters:
        - $ref: '#/components/parameters/Fingerprint'
        - $ref: '#/components/parameters/Language'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
  /game/{id}:
    get:
      tags:
        - wordle
      summary: Find game by id
      operationId: getGameById
      parameters:
        - $ref: '#/components/parameters/Id'
        - $ref: '#/components/parameters/Fingerprint'
        - $ref: '#/components/parameters/Language'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Invalid Id supplied
        '403':
          description: Forbidden
  /game/{id}/guess:
    post:
      tags:
        - wordle
      summary: Add new guess
      operationId: makeGuess
      parameters:
        - $ref: '#/components/parameters/Id'
        - $ref: '#/components/parameters/Fingerprint'
        - $ref: '#/components/parameters/Language'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Guess'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Invalid Id supplied
        '403':
          description: Forbidden
  /language/list:
    get:
      tags:
        - wordle
      summary: Get available languages
      operationId: getLanguageList
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LanguageList'
  /settings:
    get:
      tags:
        - wordle
      summary: Get game settings
      operationId: getSettings
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settings'
components:
  schemas:
    Id:
      type: integer
    Game:
      type: object
      required: [id, hash, isCompleted, guess]
      properties:
        id:
          $ref: '#/components/schemas/Id'
        hash:
          type: string
          description: sha-512 hash of the word
          example: ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff
        secret:
          type: string
          example: 'ee3c10ae'
          description: salt used for hash, presented when complete is "true"
        isCompleted:
          type: boolean
        guess:
          type: array
          items:
            $ref: '#/components/schemas/GuessResponse'
        status:
          type: string
          enum: [SUCCESS, FAIL, IN_PROGRESS]
          description: presented when complete is "true"
        word:
          type: string
          description: the word, presented when complete is "true"
          minLength: 5
          maxLength: 5
    Guess:
      type: object
      required:
        - guess
      properties:
        guess:
          type: string
          example: 'MAGIC'
          minLength: 5
          maxLength: 5
    GuessResponse:
      type: object
      required:
        - id
        - result
      properties:
        id:
          $ref: '#/components/schemas/Id'
        result:
          type: array
          items:
            $ref: '#/components/schemas/Character'
    Character:
      type: object
      required:
        - character
        - position
        - exists
      properties:
        character:
          type: string
          maxLength: 1
          minLength: 1
          example: 'a'
        position:
          type: boolean
        exists:
          type: boolean
    LanguageCode:
      type: string
      maxLength: 2
      minLength: 2
      example: 'en'
    Language:
      type: object
      required:
        - id
        - code
      properties:
        id:
          $ref: '#/components/schemas/Id'
        code:
          $ref: '#/components/schemas/LanguageCode'
    LanguageList:
      type: array
      items:
        $ref: '#/components/schemas/Language'
    Settings:
      type: object
      required:
        - wordLength
        - maxRounds
        - defaultLanguage
      properties:
        wordLength:
          type: integer
        maxRounds:
          type: integer
        defaultLanguage:
          $ref: '#/components/schemas/LanguageCode'
  parameters:
    Id:
      name: id
      in: path
      required: true
      schema:
        type: integer
    Fingerprint:
      name: X-Fingerprint
      in: header
      required: true
      schema:
        type: string
        maxLength: 20
        minLength: 20
        example: fingerprint--example
    Language:
      name: Accept-Language
      in: header
      schema:
        $ref: '#/components/schemas/LanguageCode'
